name:                to-do-app
version:             0.1.0.0
github:              "githubuser/to-do-app"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/to-do-app#readme>

dependencies:
- aeson
- base >= 4.7 && < 5
- bytestring
- directory
- listsafe
- servant
- servant-server
- string-conversions
- time
- transformers
- wai
- warp
- yaml

library:
  source-dirs: src

executables:
  to-do-app-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - to-do-app

tests:
  to-do-app-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - to-do-app
    - hspec
    - hspec-wai
    - hspec-wai-json
    - aeson
